version: '3.8'

services:
  # OpenNoiseNet Landing Page
  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    container_name: opennosienet-landing
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    networks:
      - opennosienet-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Landing page development server
  landing-dev:
    build:
      context: ./landing
      dockerfile: Dockerfile.dev
    container_name: opennosienet-landing-dev
    ports:
      - "3001:3000"
    volumes:
      - ./landing:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    networks:
      - opennosienet-network

networks:
  opennosienet-network:
    name: opennosienet-network
    external: true