[providers]
node = "18"

[phases.setup]
cmds = ["npm install -g pnpm"]

[phases.build]
cmds = ["cd landing && pnpm install", "cd landing && pnpm build"]

[phases.start]
cmd = "cd landing && pnpm start"

[variables]
NODE_ENV = "production"
PORT = "3000"