include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore
    dangling_library_doc_comments: ignore
    deprecated_member_use: ignore
    curly_braces_in_flow_control_structures: ignore
    inference_failure_on_collection_literal: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_function_return_type: ignore
    inference_failure_on_instance_creation: ignore
    prefer_const_constructors: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_non_null_assertion: ignore
    unnecessary_null_comparison: ignore
    unused_element: ignore
    unused_field: ignore
    unused_import: ignore
    unused_local_variable: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/core/gen/**"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disable rules that conflict with code generation
    avoid_annotating_with_dynamic: false
    public_member_api_docs: false

    # Additional rules for Flutter
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
