name: noisenet_mobile
description: OpenNoiseNet mobile application for environmental noise monitoring with on-device AI processing.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4

  # Network & API
  dio: ^5.3.2
  json_annotation: ^4.8.1

  # Database & Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Audio Processing & Permissions
  permission_handler: ^11.3.1
  noise_meter: ^5.0.2
  audio_waveforms: ^1.0.5
  flutter_sound: ^9.2.13
  just_audio: ^0.9.40

  # Location & Maps
  geolocator: ^10.1.0

  # UI & Navigation
  go_router: ^12.1.1
  fl_chart: ^0.68.0

  # Utilities
  path: ^1.8.3
  uuid: ^4.1.0
  
  # Background Tasks & AI/ML
  workmanager: ^0.5.2
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

  # Code Quality
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Assets will be added when needed
  # assets:
  #   - assets/images/
  #   - assets/icons/

# Dependency overrides removed - switched to flutter_sound
# dependency_overrides:
#   record_platform_interface: ^1.0.2
#   record_linux: any

# Flutter configuration will be added later when needed
# flutter_gen:
#   output: lib/core/gen/
#   line_length: 80
#   integrations:
#     flutter_svg: true

# Build flavors configuration will be added later when needed  
# flutter_flavors:
#   development:
#     app:
#       name: "NoiseNet Dev"
#     android:
#       applicationId: "org.noisenet.dev"
#     ios:
#       bundleId: "org.noisenet.dev"
#   production:
#     app:
#       name: "OpenNoiseNet"
#     android:
#       applicationId: "org.noisenet"
#     ios:
#       bundleId: "org.noisenet"